### ISSUE TITLE
Add statuses for the other branches

### ISSUE THREAD

**Issue by tzi** [piwik/ci-status#15]
Hi!

It could be useful to add statuses for other branches than master.

Maybe, in a first step, we can add a link to the associate [travis branch summary](https://travis-ci.org/tombell/travis-ci-status/branches).

What do you think abou it?

Cheers,  
Thomas.

**Comment by jfallows** [comment]
Any teams using GitFlow on GitHub would likely want to see the continuous integration status of the develop branch for their projects.

**Comment by mattab** [comment]
Thanks for the suggestion! at Piwik PRO we will also need this as we are starting to use Git flow for the Piwik plugins :+1: 

Notes/ brain dump: 
 * maybe we could let users configure the branches in the config file
 * at top of the screen we can add links like `Master branch` and `Develop branch` next to `Short by name`
 * If a branch does not exist in a repo we could show "Branch not found" or so.

thoughts?

**Comment by mnapoli** [comment]
> maybe we could let users configure the branches in the config file

which config file? If you meant a config file of this project: ci-status doesn't store a list of repositories, we can't configure the branch for each repository.

We could try to fetch both master and develop and show the one that exist (or both?). That would be pretty slow I guess (twice the amount of queries), but I don't really see an alternative.

**Comment by mattab** [comment]
> We could try to fetch both master and develop and show the one that exist (or both?)

Sounds good. 

I'm wondering whether it's better to show: 
 * status for both master and develop at same time
 * or add a "Show master" / "Show develop" toggle at the top

Slowness is not an issue as it's very fast today to load the dashboard :+1:

**Comment by mattab** [comment]
Hey @mnapoli could you work on this shortly? we need it very much for https://github.com/piwik/piwik/issues/6544 and now that some plugins use Git flow :+1:

**Comment by mnapoli** [comment]
I've implemented a first solution to be able to monitor the develop branch, please test it on https://ci-status.com/

It's not perfect but at least it will do the job right now, and I'll have a look at implementing more features when i'm finished with the issues for 2.12.

**Comment by mnapoli** [comment]
This is implemented (branch selector in the menu) and live! Only master and develop for now though.

> the green/red button should link to the actual matching build on Travis CI (currently they link to the latest build)

Done too.

**Comment by mattab** [comment]
:+1:
