### ISSUE TITLE
'No builds on master' but there are builds on master

### ISSUE THREAD

**Issue by mattab** [piwik/ci-status#16]
On the CI Status dashboard there are a few repos that appear with the message `No builds on master`

![no builds on master](https://cloud.githubusercontent.com/assets/466765/5608583/a397beca-94ed-11e4-8d80-dc041117f8d6.png)

however there are builds on `master` here: https://travis-ci.org/piwik/piwik-ui-tests/builds/45902361

refs https://github.com/piwik/piwik/issues/6544

**Comment by mnapoli** [comment]
It's because of an adblocker blocking requests containing "piwik" :p

I use uBlock, disabling it for the page solves the problem.

**Comment by mattab** [comment]
Nice, it works, adBlock also had the problem
