### ISSUE TITLE
allow to exclude builds from being reported in the dashboard

### ISSUE THREAD

**Issue by mattab** [piwik/ci-status#20]
The goal of this issue is to add little config option to exclude particular projects from being listed in the dashboard.

Sometimes, we have access to Travis CI builds because we are part of some project on Github. But in the end as a user of ci-status I do not want these builds reported in my dashboard because I don't own them. I would like to be able to configure in the config of the app deployed, that these repositories should not appear in the list. This will help me make the builds 100% green and minimise the noise for builds I do not manage.

On our own deploy at https://ci-status.com we want to exclude:
 * piwik/piwik-tests-plugins
 * piwik/piwik-python-api

refs https://github.com/piwik/piwik/issues/6544

**Comment by mnapoli** [comment]
It's online!
