### ISSUE TITLE
Detect if there is a develop branch (for gitflow) and show develop status

### ISSUE THREAD

**Issue by diosmosis** [piwik/ci-status#22]
Would be very helpful when fixing plugin builds for a new Piwik release, since master will usually stay failing until the required changes are merged into develop and then into master.

**Comment by mattab** [comment]
@diosmosis can you let @mnapoli know what ideally we would need to have a useful CI dashboard for our plugin build fixing flow?

**Comment by mnapoli** [comment]
FYI I've started implementing this change. 2 columns, master and develop. I'll see if it works out.

**Comment by diosmosis** [comment]
Would need develop branch, plus the ability to see a single branch for all builds (eg, 2_15_tests), then we'd have enough information to see all plugin compatibility in the dashboard.

**Comment by mnapoli** [comment]
So:

- master
- develop
- any other branch

For master and develop, do they need to appear both by default? Or is it fine with a select/…?

**Comment by diosmosis** [comment]
Should be ok w/ a select, just need to see the information for all the builds in one place.

**Comment by diosmosis** [comment]
:+1: yay! :)

**Comment by mnapoli** [comment]
wait a minute I'm deploying in prod ;)

**Comment by mnapoli** [comment]
OK should be good now: https://ci-status.com/

You can switch to any branch, but master and develop are pre-configured for faster access. Let me know if that's good enough. I tried to show multiple statuses at the same time but it was getting quite complex and overloaded visually…

FYI if you want to reload, just press enter in the text field (removed the button, let me know if it's a problem).
